[package]
name = "simplify"
description = "Simplifier for complex boolean expressions"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
pest = "2.7.0"
pest_derive = "2.7.0"
quine-mc_cluskey = "0.2.4"
